[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.2"
# The archive format to use for non-windows builds (defaults .tar.xz)
unix-archive = ".tar.gz"
# CI backends to support
ci = "github"
# Which actions to run on pull requests
pr-run-mode = "skip"
# Allow manual modifications to CI files
allow-dirty = ["ci"]
# Which phase dist should use to create the GitHub release
github-release = "announce"
# Whether to publish prereleases to package managers
publish-prereleases = false
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Post-announce jobs to run in CI
post-announce-jobs = ["./pages"]
github-custom-job-permissions = { pages = { contents = "read", pages = "write", id-token = "write" } }
# Whether to install an updater program
install-updater = false
# Path that installers should place binaries in
install-path = "CARGO_HOME"
