[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.2"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "npm", "homebrew"]
# A GitHub repo to push Homebrew formulas to
tap = "feliblo/homebrew-tap"
formula = "dbtective"
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
    "aarch64-apple-darwin",
    "aarch64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
]
# A namespace to use when publishing this package to the npm registry
npm-scope = "@feliblo"
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Local artifacts jobs to run in CI
local-artifacts-jobs = ["./build-binaries"]
# Publish jobs to run in CI
publish-jobs = ["./publish", "homebrew"]
post-announce-jobs = ["./pages"]
# Custom permissions for GitHub Actions jobs
github-custom-job-permissions = { "pages" = { contents = "read", pages = "write", id-token = "write" } }
# Whether to install an updater program
install-updater = false
